numbers =[12,34,23,34,23]
numbers.append(56)
print(numbers)
numbers.insert(2,56)
print(numbers)
numbers.remove(12)
print(numbers)
last=numbers.pop()
print(last,numbers)
index= numbers.index(54)
print(index)
